export const SPEAK_PROMPTS = [
  'Have something in mind? Voice it out',
  'Technology got better? Tell the world your views',
  'How is your day? Could you share some',
  'Just say something...',
  'When you speak out, you feel confident again',
  'You learnt something new? Kindly help others',
  'Any info there? Tell someone',
  'Good news? Share it with the world',
  'Share any information',
  'You are a leader. Motivate people',
  'Someone made a mistake? Correct others now',
  'Teach your religion',
  "Don't be voiceless",
  'Welcome to the voiced city. All are heard',
  'Start a conversation',
  "Most don't know what you know. Share knowledge",
  'Got a story? Let them hear it',
  'Feeling something? Put a voice on it',
  'A thought is a seed. Speak it',
  'Your accent is welcome here',
  'One minute can change a mind',
  'Say the thing you would text later',
  'Truth sounds better out loud',
  'If it moved you, it can move someone else',
  'Ask the question nobody is asking',
  'Celebrate a small win out loud',
  'Need prayer, advice, or a laugh? Speak',
  'Your village is listening',
  'Record the lesson while it is fresh',
  'Silence is easy. Voice takes courage',
  'What would you tell your younger self?',
  'News from your street? Pass it on',
  'A joke, a verse, a warning. Pick one',
  'If you can say it, someone needed it',
  'Leave a voice for the ones who cannot be here',
  'Hot take? Slide and say it',
  'Missing home? Talk to the feed',
  'Explain it like they are sitting next to you',
  'The world is noisy. Make yours clear',
  'Unfinished thought? Finish it in a note',
  'Be the first voice on this',
  'Compliment someone. They might hear it',
  'Teach a skill in sixty seconds',
  'What did you notice today?',
  'Courage is a sound. Make it',
  'Your voice is the post',
  'Drop wisdom, not just words',
  'If it is heavy, speak it lighter',
  'Call it as you see it',
  "Today's headline from your life",
  'A blessing, a rant, a recap. Go',
  'Somebody is waiting on your take',
  "Don't type it. Voice it",
  'Make the feed feel human',
  'One honest sentence is enough',
];
